services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - rag_network
  backend:
    build:
      context: ./backend
    user: "${UID}:${GID}"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OLLAMA_URL: ${OLLAMA_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_EMBEDDING_MODEL: ${OLLAMA_EMBEDDING_MODEL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_started
      ollama:
        condition: service_healthy
    networks:
      - rag_network

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag_network

  minio:
    image: pgsty/minio:RELEASE.2026-08-04T00-00-00Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - rag_network

  minio-init:
    image: pgsty/mc
    depends_on:
      - minio
    networks:
      - rag_network
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        until mc alias set local http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}; do
          sleep 1
        done
        mc mb --ignore-existing local/${MINIO_BUCKET}

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 10

  ollama-init:
    image: ollama/ollama
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: ${OLLAMA_URL}
    networks:
      - rag_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama pull ${OLLAMA_MODEL}
        ollama pull ${OLLAMA_EMBEDDING_MODEL}

volumes:
  postgres_data:
  ollama_data:
  minio_data:
  frontend_node_modules:

networks:
  rag_network: