services:

  backend:
    build:
      context: ./backend  
    user: "${UID}:${GID}"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://rag:rag@postgres:5432/rag
      OLLAMA_URL: http://ollama:11434
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_started
      ollama:
        condition: service_healthy
    networks:
      - rag_network

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: rag
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag_network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rag_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 10

  ollama-init:
    image: ollama/ollama
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: http://ollama:11434
    networks:
      - rag_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama pull gemma3:270m
        ollama pull embeddinggemma

volumes:
  postgres_data:
  ollama_data:

networks:
  rag_network:
