"""update document storage metadata

Revision ID: 8103241964b2
Revises: 09168bd4ab52
Create Date: 2026-09-23 11:45:04.540454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8103241964b2'
down_revision: Union[str, Sequence[str], None] = '09168bd4ab52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('storage_key', sa.String(length=255), nullable=False))
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'storage_key')
    op.drop_column('documents', 'content_type')
    # ### end Alembic commands ###
